# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_instance',
            name='number_of_players',
        ),
    ]
