# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Decks',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
