# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_remove_game_instance_number_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_instance',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
