# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_users_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_online',
            name='user_online',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_online', to=settings.AUTH_USER_MODEL),
        ),
    ]
