# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20170424_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_instance',
            name='number_of_players',
            field=models.IntegerField(default=0),
        ),
    ]
