# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_users_in_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_in_lobby',
            name='user_in_lobby',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='max_number_of_players',
            field=models.PositiveIntegerField(blank=True, default=2, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='number_of_players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users_in_lobby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
