# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 04:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_auto_20170428_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_in_lobby',
            name='user_in_lobby',
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='max_number_of_players',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='users_in_lobby',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
