# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_auto_20170430_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='attack_range',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hero',
            name='damage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hero',
            name='defense',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hp',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
