# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_auto_20170430_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
