# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import home_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_auto_20170430_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to=home_page.models.upload_path),
        ),
    ]
