# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0017_auto_20170430_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.Hero'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home_page.Card'),
        ),
    ]
