# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0019_auto_20170430_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='copies',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
