# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0020_card_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('hero_class', models.CharField(max_length=50, unique=True)),
                ('health', models.PositiveSmallIntegerField()),
                ('armor', models.PositiveSmallIntegerField()),
                ('attack_damage', models.PositiveSmallIntegerField()),
                ('attack_range', models.PositiveSmallIntegerField()),
                ('game_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.Game_instance')),
            ],
        ),
    ]
