# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0021_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_player',
            name='player_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
