# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0022_game_player_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_player',
            name='armor',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_player',
            name='attack_damage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_player',
            name='attack_range',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_player',
            name='health',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_player',
            name='hero_class',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
