# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0024_auto_20170501_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_player',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_class',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
