# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0025_auto_20170501_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_player',
            name='hero_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
