# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0026_auto_20170501_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_player',
            name='board_position',
            field=models.CharField(default='tile-32', max_length=10),
        ),
        migrations.AddField(
            model_name='game_player',
            name='turn_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='max_number_of_players',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
