# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0027_auto_20170503_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Hero', 'Hero'), ('Boss', 'Boss'), ('Minion', 'Minion'), ('Ability', 'Ability'), ('Augment', 'Augment'), ('Skill', 'Skill'), ('Equipment', 'Equipment'), ('Reaction', 'Reaction'), ('Ultimate', 'Ultimate')], default='Hero', max_length=20),
        ),
    ]
