# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0028_auto_20170504_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_instance',
            name='game_state',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Completed', 'Completed')], default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='room_name',
            field=models.CharField(error_messages={'unique': 'Room name already exists.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game_player',
            name='board_position',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
