# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0029_auto_20170512_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_instance',
            name='number_of_players_ready',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
